= pubsub-overlay-system
Publish Subscribe System with Structured and Unstructured Overlays - Algorithms and Distributed Systems Course 22/23 @ FCT-UNL

== Running the experiments

All experiments are defined in the `analysis/experiments.yaml` file.
The experiments can be run locally or in the cluster.
To assist with the running of the experiments, metrics collection and analysis, there are some scripts to automate the process.

=== Setup
First, the project needs to be build.
[source, bash]
----
$ mvn compile assembly:single
----

=== Running the experiments locally
To run the experiments locally use the `scripts/run-experiment.sh` script. This script takes a single argument, a regex expression that matches the experiment names to run.

.example usage
[source, bash]
----
$ scripts/run-experiment.sh '.*-config[1,2]'
----

=== Running the experiments in the cluster
To run the experiments in the cluster use the `scripts/run-experiment-in-cluster.sh` script. This script is similar to the previous one but it takes a few more arguments.
The first argument is the cluster frontend hostname, this is the name used by ssh in `ssh <hostname>`.
The second argument is the job id to use for the experiment.
The third argument is the machine name to use for the experiment.
The fourth argument is the regex expression that matches the experiment names to run.

.example usage
[source, bash]
----
$ scripts/run-experiment-in-cluster.sh cluster 16099 lugia-5 '.*-config[1,2]'
----

=== Analyzing the results
After running the experiments using one of the previous scripts the directory `analysis/experiments` should could a json file for each experiment. To analyze the results there are 2 notebooks, `analysis/plots.ipynb` and `analysis/experiment.ipynb`. The first one contains the plots used in the report and the second one is used to analyze the results of a single experiment.

== dumpster of text

[source, python]
----
# Create a binary tree
dot = graphviz.Digraph("Identifier Space")
depth = 6
for i in range(depth):
    n = 2**i
    subdot = graphviz.Digraph()
    for j in range(n):
        parent_label = f"{i-1}-{j//2}"
        label = "" if i != depth - 1 else f"{j}"
        subdot.node(f"{i}-{j}", label=label, level=f"{i}")
        if not (i == 0 and j == 0):
            dot.edge(parent_label, f"{i}-{j}")
    subdot.attr(rank="same")
    dot.subgraph(subdot)
dot
----